# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on: push

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 16
            - run: npm ci
            - run: npm test
            - name: ssh-scp-ssh-pipelines
              # You may pin to the exact commit or the version.
              # uses: cross-the-world/ssh-scp-ssh-pipelines@78e864b4890087a58248ff39320406971ca88b89
              uses: cross-the-world/ssh-scp-ssh-pipelines@v1.1.4
              env : 
                host_ip:  ${{ secrets.HOST_IP }}
                port:  ${{ secrets.PORT }}
                user:  ${{ secrets.USER }}
                password:  ${{ secrets.PASSWORD }}
              with:
                # ssh remote host
                host: ${{ secrets.HOST_IP }}
                # ssh remote port
                port: ${{ secrets.PORT }}
                # ssh remote user
                user: ${{ secrets.USER }}
                # content of ssh private key. ex raw content of ~/.ssh/id_rsa
                
                pass: ${{ secrets.PASSWORD }}
            # - name: pull the repo

                

    publish-gpr:
        needs: build
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 16
                  registry-url: https://npm.pkg.github.com/
            - run: npm ci
    
